refactor: use cross to build js binding, cli and test code

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -123,6 +123,22 @@ jobs:
             target: aarch64-unknown-linux-ohos
             strip: /home/runner/setup-ohos-sdk/linux/native/llvm/bin/llvm-strip
             linker: CARGO_TARGET_AARCH64_UNKNOWN_LINUX_OHOS_LINKER=/home/runner/setup-ohos-sdk/linux/native/llvm/bin/aarch64-unknown-linux-ohos-clang
+          # FreeBSD
+          - os: ubuntu-latest
+            target: x86_64-unknown-freebsd
+            strip: llvm-strip
+            cross: cross
+            setup: |
+              sudo apt update
+              sudo apt install -y llvm
+          - os: ubuntu-latest
+            target: aarch64-unknown-freebsd
+            build_std: true
+            strip: llvm-strip
+            cross: cross
+            setup: |
+              sudo apt update
+              sudo apt install -y llvm
 
     name: build-${{ matrix.settings.target }}
     runs-on: ${{ matrix.settings.os }}
@@ -148,10 +164,16 @@ jobs:
         if: ${{ contains(matrix.settings.target, 'ohos') }}
         uses: openharmony-rs/setup-ohos-sdk@3c181b3244cec76aaec289ab84fb00f55f2fce3f # v0.2.4
       - name: Install Rust
+        if: ${{ !matrix.settings.build_std }}
         uses: dtolnay/rust-toolchain@stable
         with:
           components: clippy, rustfmt
           targets: ${{ matrix.settings.target }}
+      - name: Install Rust
+        if: ${{ matrix.settings.build_std }}
+        uses: dtolnay/rust-toolchain@nightly
+        with:
+          components: clippy, rustfmt, rust-src
       - name: Install node.js dependencies
         working-directory: ${{ env.WORKING_DIRECTORY }}
         run: yarn install
@@ -179,6 +201,17 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
         with:
           tool: cargo-zigbuild
+      - name: Install and prepare cargo-cross
+        if: ${{ matrix.settings.cross == 'cross' }}
+        run: |
+          # install cross
+          cargo install --git https://github.com/cross-rs/cross --rev e281947ca900da425e4ecea7483cfde646c8a1ea cross
+          # copy Cross.toml to the working directory of lightningcss
+          cp Cross.toml ${{ env.WORKING_DIRECTORY }}
+          # copy the binary to the working directory
+          cp `which sccache` sccache
+          # build the image
+          docker build --tag ${{ matrix.settings.target }}:sccache --file docker/Dockerfile.${{ matrix.settings.target }} .
       - name: Setup toolchain
         if: ${{ matrix.settings.setup }}
         run: ${{ matrix.settings.setup }}
@@ -186,12 +219,12 @@ jobs:
       - name: Build release
         if: ${{ !matrix.settings.android && matrix.settings.target != 'aarch64-apple-darwin' }}
         working-directory: ${{ env.WORKING_DIRECTORY }}
-        run: npx napi build --release --platform --manifest-path ./node/Cargo.toml --target ${{ matrix.settings.target }} ${{ matrix.settings.cross == 'zig' && '-x' || matrix.settings.cross == 'napi' && '--use-napi-cross' || matrix.settings.cross == 'cross' && '--use-cross' || '' }}
+        run: npx napi build --release --platform --manifest-path ./node/Cargo.toml --target ${{ matrix.settings.target }} ${{ matrix.settings.cross == 'zig' && '-x' || matrix.settings.cross == 'napi' && '--use-napi-cross' || matrix.settings.cross == 'cross' && '--use-cross' || '' }} ${{ matrix.settings.build_std && '-- -Z build-std=std,panic_abort +nightly' || '' }}
       - name: Build CLI
         if: ${{ !matrix.settings.android && matrix.settings.target != 'aarch64-apple-darwin' }}
         working-directory: ${{ env.WORKING_DIRECTORY }}
         run: |
-          ${{ matrix.settings.linker || '' }} cargo ${{ matrix.settings.cross == 'zig' && 'zigbuild' || 'build' }} --release --features cli --target ${{ matrix.settings.target }}
+          ${{ matrix.settings.linker || '' }} ${{ matrix.settings.cross == 'cross' && 'cross' || 'cargo' }} ${{ matrix.settings.cross == 'zig' && 'zigbuild' || 'build' }} --release --features cli --target ${{ matrix.settings.target }} ${{ matrix.settings.build_std && '-Z build-std=std,panic_abort +nightly' || '' }}
           node -e "require('fs').renameSync('target/${{ matrix.settings.target }}/release/${{ env.BINARY_NAME }}', '${{ env.BINARY_NAME }}')"
 
       - name: Build release (Apple Silicon)
@@ -235,76 +268,83 @@ jobs:
           path: |
             ${{ env.WORKING_DIRECTORY }}/node/*.node
             ${{ env.WORKING_DIRECTORY }}/${{ env.BINARY_NAME }}
+      - name: Build and tests (no run)
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+        # currently for cross only
+        if: ${{ matrix.settings.cross == 'cross' }}
+        run: |
+          mkdir -p test_bins
+          cross test --all-features --no-run --target ${{ matrix.settings.target }} --message-format=json ${{ matrix.settings.build_std && '-Z build-std=std,panic_abort +nightly' || '' }} 2>cross.log | grep -E '^\{' | tee cargo-test.jsonl > /dev/null
+          cat cross.log
+          jq -r 'select(.reason=="compiler-artifact")|select(.profile.test==true)|.executable//empty' cargo-test.jsonl | sed "s|^/target|target|" | tr '\n' '\0' | xargs -0 -I{} cp "{}" test_bins/
+          cp target/${{ matrix.settings.target }}/debug/lightningcss test_bins/
+          ls -alh test_bins/
+      - name: Upload test
+        uses: actions/upload-artifact@v6
+        with:
+          name: test-${{ matrix.settings.target }}
+          path: |
+            ${{ env.WORKING_DIRECTORY }}/test_bins
 
-  build-freebsd:
+  test-freebsd-js-rust:
+    name: Test on FreeBSD ${{ matrix.version }} ${{ matrix.architecture }}
+    needs: build
     strategy:
       fail-fast: false
       matrix:
-        os:
-          - name: freebsd
-            version: "14.3"
-            architecture: x86-64
-            target: x86_64-unknown-freebsd
-          - name: freebsd
-            version: "14.3"
-            architecture: arm64
-            target: aarch64-unknown-freebsd
-    runs-on: ${{ matrix.os.architecture == 'x86-64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
-    name: Build FreeBSD ${{ matrix.os.architecture }}
+        version: ["15.0", "14.3", "13.5"]
+        architecture: ["x86-64", "arm64"]
+        exclude:
+          - version: "13.5"
+            architecture: "arm64"
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
       - uses: ./.github/actions/checkout-repo
-      - name: Install Qemu
-        run: |
-          sudo apt update
-          sudo apt install -y ${{ matrix.os.architecture == 'x86-64' && 'qemu-system-x86' || 'qemu-system-arm' }} qemu-utils
-      - name: Test and Build
-        uses: IronBlood/cross-platform-action@a26499562b2d7f1d43e8981b667110ccbb0b6698
-        env:
-          RUSTUP_IO_THREADS: 1
+      - name: Download artifacts
+        uses: actions/download-artifact@v7
         with:
-          operating_system: ${{ matrix.os.name }}
-          architecture: ${{ matrix.os.architecture }}
-          version: ${{ matrix.os.version }}
+          name: bindings-${{ matrix.architecture == 'arm64' && 'aarch64-unknown-freebsd' || 'x86_64-unknown-freebsd' }}
+          path: ${{ env.WORKING_DIRECTORY }}
+      - name: Download test
+        uses: actions/download-artifact@v7
+        with:
+          name: test-${{ matrix.architecture == 'arm64' && 'aarch64-unknown-freebsd' || 'x86_64-unknown-freebsd' }}
+          path: ${{ env.WORKING_DIRECTORY }}/test_bins
+      - uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
+        with:
+          operating_system: freebsd
+          architecture: ${{ matrix.architecture }}
+          version: ${{ matrix.version }}
           memory: 13G
           cpu_count: 3
-          environment_variables: "DEBUG RUSTUP_IO_THREADS"
           shell: bash
           run: |
-            sudo pkg install -y -f curl node npm yarn rust
-            echo "~~~~ rustc --version ~~~~"
-            rustc --version
-            echo "~~~~ node -v ~~~~"
-            node -v
-            echo "~~~~ yarn --version ~~~~"
-            yarn --version
-            # NOTE extra step because this is the real repo
+            sudo pkg install -y node npm yarn
             cd lightningcss
-            cp node/index.js node/index.js.bak
+            # test js binding
             yarn install --ignore-scripts || true
-            npx napi build --release --platform --manifest-path ./node/Cargo.toml
-            strip node/*.node
-            file node/*.node
-            mv node/index.js.bak node/index.js
             yarn test
-            cargo build --release --features cli
-            # HACK bypass the racing condition for now see issue 8
-            RAYON_NUM_THREADS=1 CARGO_TERM_COLOR=always RUST_BACKTRACE=full cargo test --all-features
-            mv target/release/lightningcss lightningcss
-            strip lightningcss
-            file lightningcss
             node -e "require('.')"
+            # check cli
+            file lightningcss
+            chmod +x lightningcss test_bins/*
             ./lightningcss --help
-            rm -rf node_modules
-            rm -rf target
-            rm -rf .yarn/cache
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: bindings-${{ matrix.os.target }}
-          path: |
-            ${{ env.WORKING_DIRECTORY }}/node/*.node
-            ${{ env.WORKING_DIRECTORY }}/lightningcss
+            export RAYON_NUM_THREADS=1
+            # run cargo test binaries
+            if [ -d test_bins ]; then
+              for bin in test_bins/*; do
+                [ -f "$bin" ] || continue
+                if [ "$(basename "$bin")" = "lightningcss" ]; then
+                  continue
+                fi
+                echo "=== $bin ==="
+                "$bin"
+              done
+            else
+              echo "test_bins directory not found"
+              exit 1
+            fi
 
   build-test-wasm:
     runs-on: ubuntu-latest
